### ISSUE TITLE
Error matching ResponseBody without 'content'

### ISSUE THREAD

**Issue by domiTEN** [byjg/php-swagger-test#49]
Hi,

I just made a pull request that should solve an issue matching response bodies like this:

```
   response:
      '401':
         $ref: '#/components/responses/Unauthorized' 
```

This is because the 'content' tag is not present and you suppose there is no body in the response.

According to swagger specification, the example above is well formed (https://swagger.io/docs/specification/describing-responses/).

Thanks!

**Comment by byjg** [comment]
Thank you so much. I just added two comments there. The most important is, if possible, add a unit test to validate the new feature.

**Comment by domiTEN** [comment]
Just added the unit test. Anything, just let me know.

Thanks!

**Comment by byjg** [comment]
I merged your PR into branch 3.1. It will be general available in the next release.

**Comment by domiTEN** [comment]
Thanks a lot! Do you know when version 3.1 will be available?

**Comment by byjg** [comment]
Probably end of next week. If you want you can use the version `3.1.x-dev`.

**Comment by domiTEN** [comment]
Hi!

I have seen the release 3.1 is still not available? I would like to use it in my project. Is there any issue? Do you know when it will be available?

Thanks!

**Comment by byjg** [comment]
My plan is release in the end of this week. I changed other components I have and some are dependencies of the Swagger Test. I already start to merge them.

**Comment by UlrichEckhardt** [comment]
domiTEN, I installed the release candidate using
```
composer require --dev --update-with-dependencies byjg/swagger-test=3.1.x-dev byjg/webrequest=dev-psr7
```
You can do the same and provide some feedback if things still work for you.

**Comment by domiTEN** [comment]
Thanks@UlrichEckhardt! It worked!
